[pytest]
# Default command line options:
# -v: verbose (detailed output with test names)
# -s: allow print statements to show in console (stdout)
# --tb=short: shorter traceback format when tests fail (cleaner logs)
addopts = -v -s --tb=short

# Define where pytest should look for tests
testpaths = tests

# Registered markers to prevent "PytestUnknownMarkWarning"
# We will use these decorators later like @pytest.mark.sanity
markers =
    sanity: Critical sanity checks
    regression: Full regression suite
    api: API integration tests
    negative: Negative testing scenarios